name: ${APP_NAME}

services:
  traefik:
    image: traefik:v3.3

  mysql:
    image: mysql:8.0

  laravel:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    depends_on:
      - traefik
      - mysql